name: TestNotify

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Recover Ruby dependency cache
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-rubydeps-
            ${{ runner.OS }}-
      - run: bundle install --path vendor/bundle --jobs 4 --retry 3
        name: Install Ruby deps

      - name: Lint and Rubocop
        run: |
          bundle exec rubocop
          bundle exec erblint app/{cells,views}/**/*.erb

      - name: Setup Database
        run: bundle exec rake test_app
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres

      # - name: Setup Code Climate test-reporter
      #   run: |
      #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #     chmod +x ./cc-test-reporter
      #     ./cc-test-reporter before-build

      - name: Run RSpec
        run: COBERTURA=1 bundle exec rake
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres

      - uses: actions/checkout@master
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/coverage.xml

      # - name: Publish code coverage
      #   run: |
      #     export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
      #     ./cc-test-reporter after-build -r "$CC_TEST_REPORTER_ID"
      #   env:
      #     CC_TEST_REPORTER_ID: afec4e0521370c5dfcd26d2bcdf7d0d21fcd6545bc3e377b88e51e827b8acdaf
